worker_processes auto;
error_log /dev/stderr notice;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;
    access_log /dev/stdout combined;
    sendfile on;
    keepalive_timeout 30;
    client_body_temp_path /var/cache/nginx/client_temp;
    proxy_temp_path /var/cache/nginx/proxy_temp;
    map $https $hsts_header {
        default "";
        on "max-age=31536000";
    }
    include /etc/nginx/conf.d/server.conf;
}
