/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Change */
        post: operations["password_change_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/business-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_api_v1_business_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Profile */
        patch: operations["patch_profile_api_v1_business_profile_patch"];
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clients */
        get: operations["clients_api_v1_clients_get"];
        put?: never;
        /** Add Client */
        post: operations["add_client_api_v1_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_v1_clients__client_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Client */
        patch: operations["update_client_api_v1_clients__client_id__patch"];
        trace?: never;
    };
    "/api/v1/clients/{client_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Client */
        post: operations["archive_client_api_v1_clients__client_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Equipment */
        get: operations["equipment_api_v1_clients__client_id__equipment_get"];
        put?: never;
        /** Add Equipment */
        post: operations["add_equipment_api_v1_clients__client_id__equipment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/equipment/{equipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Equipment */
        get: operations["get_equipment_api_v1_clients__client_id__equipment__equipment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Equipment */
        patch: operations["update_equipment_api_v1_clients__client_id__equipment__equipment_id__patch"];
        trace?: never;
    };
    "/api/v1/clients/{client_id}/equipment/{equipment_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Equipment */
        post: operations["archive_equipment_api_v1_clients__client_id__equipment__equipment_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/equipment/{equipment_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Equipment */
        post: operations["restore_equipment_api_v1_clients__client_id__equipment__equipment_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Client */
        post: operations["restore_client_api_v1_clients__client_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client Timeline */
        get: operations["client_timeline_api_v1_clients__client_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Public Quote */
        get: operations["read_public_quote_api_v1_public_quote_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/quote/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Public Quote */
        post: operations["approve_public_quote_api_v1_public_quote_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/quote/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Quote Logo */
        get: operations["public_quote_logo_api_v1_public_quote_logo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quotes */
        get: operations["quotes_api_v1_quotes_get"];
        put?: never;
        /** Add Quote */
        post: operations["add_quote_api_v1_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{quote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["get_quote_api_v1_quotes__quote_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Quote */
        patch: operations["update_quote_api_v1_quotes__quote_id__patch"];
        trace?: never;
    };
    "/api/v1/quotes/{quote_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_quotes__quote_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{quote_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate */
        post: operations["duplicate_api_v1_quotes__quote_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{quote_id}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quote Logo */
        get: operations["quote_logo_api_v1_quotes__quote_id__logo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{quote_id}/public-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Public Access */
        post: operations["rotate_public_access_api_v1_quotes__quote_id__public_access_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{quote_id}/public-access/{access_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Public Access */
        post: operations["revoke_public_access_api_v1_quotes__quote_id__public_access__access_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{quote_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Quote */
        post: operations["issue_quote_api_v1_quotes__quote_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{quote_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quote Timeline */
        get: operations["quote_timeline_api_v1_quotes__quote_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Add User */
        post: operations["add_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable User */
        post: operations["disable_user_api_v1_users__user_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable User */
        post: operations["enable_user_api_v1_users__user_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset User */
        post: operations["reset_user_api_v1_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveInput */
        ApproveInput: {
            /**
             * Accept
             * @constant
             */
            accept: true;
        };
        /** BusinessProfileData */
        BusinessProfileData: {
            /** Address */
            address: string | null;
            /** Business Timezone */
            business_timezone: string | null;
            /** Business Today */
            business_today: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            /** Id */
            id: number;
            /** Is Complete */
            is_complete: boolean;
            /** Missing Fields */
            missing_fields: string[];
            /** Phone */
            phone: string | null;
            /** Timezone */
            timezone: string | null;
            /** Trade Name */
            trade_name: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** BusinessProfilePatch */
        BusinessProfilePatch: {
            /**
             * Acknowledge Timezone Change
             * @default false
             */
            acknowledge_timezone_change: boolean;
            /** Address */
            address?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Trade Name */
            trade_name?: string | null;
        };
        /** BusinessProfileResponse */
        BusinessProfileResponse: {
            data: components["schemas"]["BusinessProfileData"];
        };
        /** CancelInput */
        CancelInput: {
            /** Reason */
            reason: string;
        };
        /** ChangePasswordInput */
        ChangePasswordInput: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Address */
            address?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** ClientData */
        ClientData: {
            /** Address */
            address: string | null;
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            links: components["schemas"]["ClientLinks"];
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Phone */
            phone: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "ARCHIVED";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ClientLinks */
        ClientLinks: {
            /** Equipment */
            equipment: string;
            /** Timeline */
            timeline: string;
        };
        /** ClientPage */
        ClientPage: {
            /** Data */
            data: components["schemas"]["ClientSummary"][];
            page: components["schemas"]["PageData"];
        };
        /** ClientPatch */
        ClientPatch: {
            /** Address */
            address?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name?: string;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** ClientResponse */
        ClientResponse: {
            data: components["schemas"]["ClientData"];
        };
        /** ClientSummary */
        ClientSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "ARCHIVED";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** EmptyInput */
        EmptyInput: Record<string, never>;
        /** EquipmentCreate */
        EquipmentCreate: {
            /** Brand */
            brand?: string | null;
            /** Location Description */
            location_description?: string | null;
            /** Model */
            model?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Serial Number */
            serial_number?: string | null;
        };
        /** EquipmentData */
        EquipmentData: {
            /** Archived At */
            archived_at: string | null;
            /** Brand */
            brand: string | null;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location Description */
            location_description: string | null;
            /** Model */
            model: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Serial Number */
            serial_number: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "ARCHIVED";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** EquipmentPage */
        EquipmentPage: {
            /** Data */
            data: components["schemas"]["EquipmentSummary"][];
            page: components["schemas"]["PageData"];
        };
        /** EquipmentPatch */
        EquipmentPatch: {
            /** Brand */
            brand?: string | null;
            /** Location Description */
            location_description?: string | null;
            /** Model */
            model?: string | null;
            /** Name */
            name?: string;
            /** Notes */
            notes?: string | null;
            /** Serial Number */
            serial_number?: string | null;
        };
        /** EquipmentResponse */
        EquipmentResponse: {
            data: components["schemas"]["EquipmentData"];
        };
        /** EquipmentSummary */
        EquipmentSummary: {
            /** Brand */
            brand: string | null;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location Description */
            location_description: string | null;
            /** Model */
            model: string | null;
            /** Name */
            name: string;
            /** Serial Number */
            serial_number: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "ARCHIVED";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Fields */
            fields?: components["schemas"]["ErrorItem"][];
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorItem */
        ErrorItem: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** IssuedPublicAccess */
        IssuedPublicAccess: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Share Url */
            share_url: string;
        };
        /** LoginInput */
        LoginInput: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** PageData */
        PageData: {
            /** Number */
            number: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PublicAccessData */
        PublicAccessData: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** PublicAccessIssuedResponse */
        PublicAccessIssuedResponse: {
            data: components["schemas"]["IssuedPublicAccess"];
        };
        /** PublicAccessResponse */
        PublicAccessResponse: {
            data: components["schemas"]["PublicAccessData"];
        };
        /** PublicApprovalData */
        PublicApprovalData: {
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
            /**
             * Status
             * @constant
             */
            status: "APPROVED";
        };
        /** PublicApprovalResponse */
        PublicApprovalResponse: {
            data: components["schemas"]["PublicApprovalData"];
        };
        /** PublicBusiness */
        PublicBusiness: {
            /** Address */
            address: string;
            /** Email */
            email: string;
            /** Has Logo */
            has_logo: boolean;
            /** Phone */
            phone: string;
            /** Trade Name */
            trade_name: string;
        };
        /** PublicClient */
        PublicClient: {
            /** Name */
            name: string;
        };
        /** PublicQuoteData */
        PublicQuoteData: {
            /** Approved At */
            approved_at: string | null;
            business: components["schemas"]["PublicBusiness"];
            /**
             * Business Today
             * Format: date
             */
            business_today: string;
            /** Can Approve */
            can_approve: boolean;
            client: components["schemas"]["PublicClient"];
            /**
             * Currency
             * @constant
             */
            currency: "BRL";
            /** Is Expired */
            is_expired: boolean;
            /** Items */
            items: components["schemas"]["PublicQuoteItem"][];
            /** Notes */
            notes: string | null;
            /** Number */
            number: string;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /**
             * Server Now
             * Format: date-time
             */
            server_now: string;
            /**
             * Status
             * @enum {string}
             */
            status: "SENT" | "APPROVED";
            /** Subtotal */
            subtotal: string;
            /** Total */
            total: string;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
        };
        /** PublicQuoteItem */
        PublicQuoteItem: {
            /** Description */
            description: string;
            /** Line Total */
            line_total: string;
            /** Position */
            position: number;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string;
        };
        /** PublicQuoteResponse */
        PublicQuoteResponse: {
            data: components["schemas"]["PublicQuoteData"];
        };
        /** QuoteCreate */
        QuoteCreate: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Items */
            items?: components["schemas"]["QuoteItemInput"][];
            /** Notes */
            notes?: string | null;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
        };
        /** QuoteDetail */
        QuoteDetail: {
            /** Approved At */
            approved_at: string | null;
            /** Cancellation Reason */
            cancellation_reason: string | null;
            /** Cancelled At */
            cancelled_at: string | null;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Commercial Snapshot */
            commercial_snapshot: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Currency
             * @constant
             */
            currency: "BRL";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Expired */
            is_expired: boolean;
            /** Items */
            items: components["schemas"]["QuoteItemData"][];
            /** Notes */
            notes: string | null;
            /** Number */
            number: string;
            public_access: components["schemas"]["PublicAccessData"] | null;
            /** Sent At */
            sent_at: string | null;
            /** Source Quote Id */
            source_quote_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "SENT" | "APPROVED" | "CANCELLED";
            /** Subtotal */
            subtotal: string;
            /** Total */
            total: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
            /** Version */
            version: number;
        };
        /** QuoteIssuedResponse */
        QuoteIssuedResponse: {
            data: components["schemas"]["QuoteDetail"];
            public_access: components["schemas"]["IssuedPublicAccess"];
        };
        /** QuoteItemData */
        QuoteItemData: {
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Line Total */
            line_total: string;
            /** Position */
            position: number;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string;
        };
        /** QuoteItemInput */
        QuoteItemInput: {
            /** Description */
            description: string;
            /** Id */
            id?: string | null;
            /** Position */
            position: number;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string;
        };
        /** QuotePage */
        QuotePage: {
            /** Data */
            data: components["schemas"]["QuoteSummary"][];
            page: components["schemas"]["PageData"];
        };
        /** QuotePatch */
        QuotePatch: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id?: string;
            /** Items */
            items?: components["schemas"]["QuoteItemInput"][];
            /** Notes */
            notes?: string | null;
            /**
             * Valid Until
             * Format: date
             */
            valid_until?: string;
        };
        /** QuoteResponse */
        QuoteResponse: {
            data: components["schemas"]["QuoteDetail"];
        };
        /** QuoteSummary */
        QuoteSummary: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Currency
             * @constant
             */
            currency: "BRL";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Expired */
            is_expired: boolean;
            /** Number */
            number: string;
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "SENT" | "APPROVED" | "CANCELLED";
            /** Subtotal */
            subtotal: string;
            /** Total */
            total: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
            /** Version */
            version: number;
        };
        /** RotateInput */
        RotateInput: {
            /** Expected Access Id */
            expected_access_id: string | null;
        };
        /** SessionData */
        SessionData: {
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Idle Expires At
             * Format: date-time
             */
            idle_expires_at: string;
            /**
             * Server Now
             * Format: date-time
             */
            server_now: string;
            user: components["schemas"]["UserData"];
        };
        /** SessionResponse */
        SessionResponse: {
            data: components["schemas"]["SessionData"];
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Name */
            name: string;
        };
        /** UserData */
        UserData: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Must Change Password */
            must_change_password: boolean;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /** UserPage */
        UserPage: {
            /** Data */
            data: components["schemas"]["UserData"][];
            /** Page */
            page: {
                [key: string]: number;
            };
        };
        /** UserPatch */
        UserPatch: {
            /** Name */
            name: string;
        };
        /** UserResponse */
        UserResponse: {
            data: components["schemas"]["UserData"];
        };
        /** UserSecretResponse */
        UserSecretResponse: {
            data: components["schemas"]["UserData"];
            /** Temporary Password */
            temporary_password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** TimelineActor */
        app__modules__clients__schemas__TimelineActor: {
            /** Display Name */
            display_name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "USER" | "SYSTEM_AUTOMATION";
        };
        /** TimelineData */
        app__modules__clients__schemas__TimelineData: {
            actor: components["schemas"]["app__modules__clients__schemas__TimelineActor"];
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** TimelinePage */
        app__modules__clients__schemas__TimelinePage: {
            /** Data */
            data: components["schemas"]["app__modules__clients__schemas__TimelineData"][];
            page: components["schemas"]["PageData"];
        };
        /** TimelineActor */
        app__modules__quotes__schemas__TimelineActor: {
            /** Display Name */
            display_name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "USER" | "CUSTOMER_QUOTE_LINK" | "SYSTEM_AUTOMATION";
        };
        /** TimelineData */
        app__modules__quotes__schemas__TimelineData: {
            actor: components["schemas"]["app__modules__quotes__schemas__TimelineActor"];
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** TimelinePage */
        app__modules__quotes__schemas__TimelinePage: {
            /** Data */
            data: components["schemas"]["app__modules__quotes__schemas__TimelineData"][];
            page: components["schemas"]["PageData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    password_change_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    /** @description Segundos até nova tentativa */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    read_profile_api_v1_business_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do perfil */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessProfileResponse"];
                };
            };
        };
    };
    patch_profile_api_v1_business_profile_patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessProfilePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do perfil */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clients_api_v1_clients_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: "ACTIVE" | "ARCHIVED";
                q?: string | null;
                sort?: "name" | "-name" | "created_at" | "-created_at";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_client_api_v1_clients_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_v1_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_v1_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_client_api_v1_clients__client_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    equipment_api_v1_clients__client_id__equipment_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: "ACTIVE" | "ARCHIVED";
                q?: string | null;
                sort?: "name" | "-name" | "created_at" | "-created_at";
            };
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_equipment_api_v1_clients__client_id__equipment_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_equipment_api_v1_clients__client_id__equipment__equipment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
                equipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_equipment_api_v1_clients__client_id__equipment__equipment_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                client_id: string;
                equipment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_equipment_api_v1_clients__client_id__equipment__equipment_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                client_id: string;
                equipment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_equipment_api_v1_clients__client_id__equipment__equipment_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                client_id: string;
                equipment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_client_api_v1_clients__client_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_timeline_api_v1_clients__client_id__timeline_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__modules__clients__schemas__TimelinePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_public_quote_api_v1_public_quote_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicQuoteResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    /** @description Segundos até nova tentativa */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    approve_public_quote_api_v1_public_quote_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicApprovalResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    /** @description Segundos até nova tentativa */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    public_quote_logo_api_v1_public_quote_logo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Successful Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    /** @description Segundos até nova tentativa */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    quotes_api_v1_quotes_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: ("DRAFT" | "SENT" | "APPROVED" | "CANCELLED") | null;
                client_id?: string | null;
                is_expired?: boolean | null;
                q?: string | null;
                sort?: "number" | "-number" | "created_at" | "-created_at" | "valid_until" | "-valid_until";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_quote_api_v1_quotes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_api_v1_quotes__quote_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do orçamento */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_quote_api_v1_quotes__quote_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuotePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do orçamento */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_quotes__quote_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do orçamento */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_api_v1_quotes__quote_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_logo_api_v1_quotes__quote_id__logo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_public_access_api_v1_quotes__quote_id__public_access_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAccessIssuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_public_access_api_v1_quotes__quote_id__public_access__access_id__revoke_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                quote_id: string;
                access_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_quote_api_v1_quotes__quote_id__send_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteIssuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_timeline_api_v1_quotes__quote_id__timeline_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__modules__quotes__schemas__TimelinePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
                role?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSecretResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_user_api_v1_users__user_id__disable_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_user_api_v1_users__user_id__enable_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_user_api_v1_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    /** @description Versão forte do recurso */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSecretResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    /** @description Segundos até nova tentativa */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
